=== echemdb/metadata-schema/schemas/schema.json
{   
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "id",
    "title": "echemdb metadata schema",
    "description": "This is the schema providing metadata of electrochemical measurements hosted on the echemdb website.",
    "not":
    {
        "comment": "This is preload of 'grandchild' dependencies. It is required due to the jsonschema lib issues. See https://github.com/Julian/jsonschema/issues/398.",
        "anyOf":
        [
            { "$ref": "file:electrochemical_system/component.json" },
            { "$ref": "file:electrochemical_system/electrode.json" }
        ]
    },
    "type": "object",
    "properties": {
      "source": {"$ref": "https://raw.githubusercontent.com/echemdb/metadata-schema/main/schemas/source.json"},
      "curation": {"$ref": "file:curation.json"},
      "figureDescription": {"$ref": "file:figure_description.json"},
      "electrochemicalSystem": {"$ref": "file:electrochemical_system.json"}
    }
}

=== echemdb/metadata-schema/tests/test.json
{
    "source": {
        "version": 1,
        "doi": "10.18725/OPARU-40748",
        "url": "https://oparu.uni-ulm.de/xmlui/handle/123456789/40824",
        "techniques": [ "CV" ],
        "figure": "4.1.4",
        "curve": "black",
        "bib": "some bib file name"
    },
    "curation": {
        "version": 1,
        "process": [
            {
                "role": "experimentalist",
                "name": "Johannes Hermann",
                "date": "2021-09-27"
            }
        ]
    },
    "figureDescription": {
        "version": 1,
        "comment": "some comment",
        "type": "raw",
        "measurementType": "cyclic voltammetry",
        "scanRate": {
            "value": 10,
            "unit": "mV s⁻¹"
            },
        "axes": [
            {
            "quantity": "E",
            "type": "type?",
            "unit": "V",
            "reference": "MSE",
            "orientation": "x"
            },
            {
            "quantity": "j",
            "type": "type?",
            "unit": "µA cm⁻²",
            "orientation": "x"
            }
        ]
    },
    "electrochemicalSystem": {
        "version": 1,
        "instrumentation": [{
                "type": "potentiostat",
                "model": "Autolab 128N",
                "manufacturer": "Metrohm"
            }
        ],
        "electrolyte": {
                "components": [
                    {"name": "electrolyte name"}
                ],
                "pH": {
                        "value": 1,
                        "uncertainty": {
                            "value": 0.1
                        }
                },
                "temperature": {
                        "value": 23,
                        "unit": "°C"
                }
        },
        "electrodes":  [{ "electrodeMaterial": "working electrode" }]
    }
}
